name: workflow1

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  workflow1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: echo "Running workflow1..."
